language: python
arch: 
  - amd64
python:
  - 3.4
  - 3.5
  - 3.6

sudo: required

install:
  - pip install cryptography scapy
  #- sudo apt-get install tcpdump python3-crypto ipython3

script:
  - cd test
  - sudo ./run_tests
